### ISSUE TITLE
DrawLineAa draws incorrect width line

### ISSUE THREAD

**Issue by diontools** [reneschulte/WriteableBitmapEx#45]
Hello. Thank you for your great project! 👍 
In the code below, DrawLineAa draws very thick line.

```csharp
var wb = BitmapFactory.New(1024, 1024);

wb.DrawLineAa(500, -500, 501, 500, Colors.Blue, 1); // incorrect width
wb.DrawLine(500, -500, 501, 500, Colors.Red); // 1px width

this.image.Source = wb;
```

capture:
![incorrect-width](https://user-images.githubusercontent.com/12995573/64505467-ee264880-d30e-11e9-9eaa-051fb112ebe0.png)

**Comment by reneschulte** [comment]
Hmm, just double checked, it should actually be clipped nicely but seems it's a straight line we are hitting a floating point rounding error. 
As a workaround you can set y1 to be 0 instead of being outside the drawing region with a negative value. It would be clipped to 0 anyway. Also you can make the line wider than just 1 that would also avoid the rounding to null width.

**Comment by reneschulte** [comment]
Just added a check that should prevent that and your code should work as it is w/o a workaround.
Make sure to use the code from commit 4d4f130d4f84c2beaa756b734a778c98fecfa22d
