### ISSUE TITLE
System.AccessViolationException when trying to resize the WriteableBitmap

### ISSUE THREAD

**Issue by rikyuz** [reneschulte/WriteableBitmapEx#64]
The Resize extension method throws an exception when trying to execute it.

In my software I'm trying to perform the resize on my WriteableBitmap like so:

`_writeableBitmap.Resize((int)(imageData.Width * scale), (int)(imageData.Height * scale),
                    WriteableBitmapExtensions.Interpolation.NearestNeighbor);`

However it crashes in the `public unsafe static int[] Resize(int* pixels, int widthSource, int heightSource, int width, int height, Interpolation interpolation)` method in the WriteableBitmapExtensions.cs.

It happens in the inner for loop where I added comment:

```
int srcIdx2 = 0;
for (int y2 = 0; y2 < height; y2++)
{
	for (int x2 = 0; x2 < width; x2++)
	{
		float sx = (float)x2 * xs;
		float num8 = (float)y2 * ys;
		int x3 = (int)sx;
		int y3 = (int)num8;
		pd[srcIdx2++] = pixels[y3 * widthSource + x3]; // The exception is thrown from this line
	}
}
```

The exception message is:

> System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

**Comment by reneschulte** [comment]
Looks like some miscalculation with the index due to rounding errors likely. Do you have a repro for this? 
A workaround might be to use a slightly different scaling factor.

**Comment by rikyuz** [comment]
I tried to use another image for the resize. This time I created the WriteableBitmap with the BitmapFactory like in the example in this repo:

`_writeableBitmap = BitmapFactory.FromResource("Resources/Images/test.png");`

With this image the resize didn't throw an exception so maybe it has something to do with the type of image I originally had? In my software the WriteableBitmap is created like so:

`_writeableBitmap = new WriteableBitmap(imageData.Width, imageData.Height, 96, 96, PixelFormats.Gray16, null);`

Then I'm writing pixels to the WriteableBitmap from an `ushort` array of the pixel data like so:

```
Int32Rect rect = new Int32Rect(0, 0, imageData.Width, imageData.Height);
_writeableBitmap.Lock();
_writeableBitmap.WritePixels(rect, imageData.Pixels, imageData.Width * 2, 0);
_writeableBitmap.AddDirtyRect(rect);
_writeableBitmap.Unlock();
```

I have poor understanding of these image formats so I'm struggling to understand why this type of image might cause the exception on the resize method but the other one created from the PNG file didn't. Does the resize method assume that the resizable image is in some other "flavor" of bitmap? Different PixelFormat perhaps?

**Comment by reneschulte** [comment]
I see you are using WPF or similar. Since there we use low-level pixel manipulation with pointers and stuff, you have to create your WB via the BitmapFactory and use the BitmapContext to avoid any pointer access issues. There's also a New overload like this which should work for you: 

`_writeableBitmap = BitmapFactory.New(imageData.Width, imageData.Height)

In general it is recommend to always use the BitmapContext. 

I'd recommend that you check some of the samples in order to see how to properly use it with BitmapFactory fro creation and also BitmapContext for manipulation like calling Resize.
https://github.com/reneschulte/WriteableBitmapEx/blob/master/Source/WriteableBitmapExShapeSample.Wpf/MainWindow.xaml.cs
